/**
 * ID: template
 * Description: 模板
 */
CREATE TABLE F2001 ( 
/*模板序号*/ TTID NUMBER(8,0) , 
/*模板名称*/ TTNAME NVARCHAR2(32) , 
/*模板类型*/ TTTYPE NVARCHAR2(1) );
ALTER TABLE F2001 ADD CONSTRAINT F2001_PRIMARY PRIMARY KEY ( TTID );
CREATE SEQUENCE F2001_TTID MINVALUE 0 START WITH 1;