/**
 * ID: templatemeasurements
 * Description: 模板测量
 */
CREATE TABLE F2003 ( 
/*测量序号*/ TSID NUMBER(8,0) , 
/*规程序号*/ TSTPID NUMBER(8,0) , 
/*排序*/ TSSEQ NUMBER(2,0) , 
/*测量名称*/ TSNAME NVARCHAR2(12) , 
/*枚举类型编号*/ TSETID NVARCHAR2(4) , 
/*照片必须性*/ TSPHOTO NUMBER(1,0) );
ALTER TABLE F2003 ADD CONSTRAINT F2003_PRIMARY PRIMARY KEY ( TSID );
ALTER TABLE F2003 ADD CONSTRAINT F2003_UNIQUE_1 UNIQUE ( TSTPID , TSSEQ );
ALTER TABLE F2003 ADD CONSTRAINT F2003_REFERENCE_1 FOREIGN KEY ( TSETID ) REFERENCES F0004 ( ETID );
ALTER TABLE F2003 ADD CONSTRAINT F2003_REFERENCE_2 FOREIGN KEY ( TSTPID ) REFERENCES F2002 ( TPID );
CREATE SEQUENCE F2003_TSID MINVALUE 0 START WITH 1;