/**
 * ID: room
 * Description: 机房
 */
CREATE TABLE F1200 ( 
/*机房序号*/ RMID NUMBER(8,0) , 
/*机房短号*/ RMSERIAL NVARCHAR2(16) , 
/*JDE地址号*/ RMAN8 NUMBER(8,0) , 
/*机房名称*/ RMNAME NVARCHAR2(16) , 
/*班组序号*/ RMCWID NUMBER(8,0) );
ALTER TABLE F1200 ADD CONSTRAINT F1200_PRIMARY PRIMARY KEY ( RMID );
ALTER TABLE F1200 ADD CONSTRAINT F1200_REFERENCE_1 FOREIGN KEY ( RMCWID ) REFERENCES F3003 ( CWID );
CREATE SEQUENCE F1200_RMID MINVALUE 0 START WITH 1;