/**
 * ID: equipment
 * Description: 设备
 */
CREATE TABLE F1201 ( 
/*设备序号*/ EQID NUMBER(8,0) , 
/*设备短号*/ EQSERIAL NVARCHAR2(16) , 
/*JDE资产号*/ EQNUMB NUMBER(8,0) , 
/*设备名称*/ EQNAME NVARCHAR2(16) , 
/*班组序号*/ EQCWID NUMBER(8,0) );
ALTER TABLE F1201 ADD CONSTRAINT F1201_PRIMARY PRIMARY KEY ( EQID );
ALTER TABLE F1201 ADD CONSTRAINT F1201_REFERENCE_1 FOREIGN KEY ( EQCWID ) REFERENCES F3003 ( CWID );
CREATE SEQUENCE F1201_EQID MINVALUE 0 START WITH 1;