/**
     * ID: crewuser
     * Description: 班组用户关系
     */
CREATE VIEW V30031 AS SELECT 
/*序号*/ t0.CUID CUID , 
/*班组序号*/ t0.CUCWID CUCWID , 
/*班组名称*/ t1.CWNAME CUCWNAME , 
/*工作中心编号*/ t2.WCMCU CUWCMCU , 
/*工作中心名称*/ t2.WCDL01 CUWCDL01 , 
/*用户序号*/ t0.CUUSID CUUSID , 
/*用户姓名*/ t3.USNAME CUUSNAME FROM F30031 t0
LEFT JOIN (SELECT CWID, CWNAME, CWWCMCU FROM V3003) t1 ON t1.CWID = t0.CUCWID
LEFT JOIN (SELECT WCMCU, WCDL01 FROM V3000) t2 ON t2.WCMCU = t1.CWWCMCU
LEFT JOIN (SELECT USID, USNAME FROM V0092) t3 ON t3.USID = t0.CUUSID;
