/**
 * ID: templateprocedure
 * Description: 模板规程
 */
CREATE TABLE F2002 ( 
/*规程序号*/ TPID NUMBER(8,0) , 
/*模板序号*/ TPTTID NUMBER(8,0) , 
/*顺序*/ TPSEQ NUMBER(4,0) , 
/*规程描述*/ TPDESCRIPTION NVARCHAR2(128) , 
/*照片必须性*/ TPPHOTO NUMBER(1,0) );
ALTER TABLE F2002 ADD CONSTRAINT F2002_PRIMARY PRIMARY KEY ( TPID );
ALTER TABLE F2002 ADD CONSTRAINT F2002_UNIQUE_1 UNIQUE ( TPTTID , TPSEQ );
ALTER TABLE F2002 ADD CONSTRAINT F2002_REFERENCE_1 FOREIGN KEY ( TPTTID ) REFERENCES F2001 ( TTID );
CREATE SEQUENCE F2002_TPID MINVALUE 0 START WITH 1;